import EStyleSheet from 'react-native-extended-stylesheet';

export const styles = EStyleSheet.create({
  datePickerStyle: {
    width: '100%',
    marginBottom: 10,
  },
  mainView: {
    backgroundColor: '#FFF',
  },
  modal: {
    height: '100%',
    overflow: 'hidden',
  },
  container: {
    paddingHorizontal: 15,
  },
  headerImage: {
    position: 'absolute',
    right: 20,
    top: 10,
    width: 111,
    height: 115,
  },
  headerBG: {
    position: 'relative',
    height: 180,
    width: '100%',
    backgroundColor: '#EDB43C',
    // backgroundColor: '#FFF',
  },
  titleText: {
    position: 'absolute',
    top: 30,
    left: 0,
    color: '#000',
    fontSize: 22,
    textAlign: 'left',
  },
  roudedLayout: {
    position: 'relative',
    marginTop: -36,
    paddingHorizontal: 15,
    paddingVertical: 30,
    backgroundColor: '#FFF',
    borderTopRightRadius: 36,
    borderTopLeftRadius: 36,
  },
  listWrap: {
    marginTop: 20,
  },
  topSection: {
    borderWidth: 1,
    borderColor: '#888',
    paddingVertical: 10,
    marginBottom: 30,
    flexDirection: 'row',
    borderRadius: 8,
    justifyContent: 'center',
  },
  topInfoWrap: {
    paddingHorizontal: 10,
    width: '33.33%',
  },
  aminityInfo: {
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 8,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  parkingImg: {
    width: 30,
    height: 30,
  },
  SecurityImg: {
    width: 24,
    height: 30,
  },
  parkingInfo: {
    backgroundColor: '#F3F1EE',
  },
  securityInfo: {
    backgroundColor: '#FFEFE7',
  },
  dropdownContainer: {
    borderBottomColor: '#000',
    borderBottomWidth: 1,
    marginBottom: 10,
    paddingLeft: 5,
  },
  inputContainer: {
    marginBottom: 5,
    paddingTop: 10,
    // paddingBottom: 10
  },
  fitnessInfo: {
    backgroundColor: '#EFF9F8',
  },
  parkingTitle: {
    color: '#333689',
  },
  securityTitle: {
    color: '#93502F',
  },
  fitnessTitle: {
    color: '#358B82',
  },
  buildingInfoTitle: {
    fontSize: 28,
    color: '#555',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderColor: '#888',
  },
  aminityLeft: {
    width: '20%',
  },
  aprtmentInfoWrap: {
    width: '100%',
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderColor: '#888',
  },
  appInfoTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  appInfoDesc: {
    fontSize: 16,
    color: '#555',
  },
  aminityIcon: {
    display: 'flex',
    alignItems: 'center',
    width: 56,
    backgroundColor: '#FFF',
    padding: 10,
    borderRadius: 8,
    justifyContent: 'center',
  },
  aminityRight: {
    width: '80%',
  },
  aminityTitle: {
    width: '100%',
    fontSize: 20,
    marginBottom: 5,
    fontWeight: 'bold',
    textAlign: 'right',
  },
  aminityArea: {
    width: '100%',
    fontSize: 16,
    color: '#888',
    textAlign: 'right',
  },
  aminityDetail: {
    width: '100%',
    color: '#888',
    fontSize: 12,
    textAlign: 'right',
  },
  borderRight: {
    borderRightWidth: 1,
    borderColor: '#999',
  },
  infoLbl: {
    width: '100%',
    marginBottom: 5,
    textAlign: 'center',
    fontSize: 16,
  },
  infoAns: {
    width: '100%',
    textAlign: 'center',
    fontSize: 16,
    fontWeight: 'bold',
  },
  statusOpen: {
    textAlign: 'center',
    fontSize: 14,
    fontWeight: 'bold',
    backgroundColor: 'green',
    borderRadius: 5,
    paddingTop: 3,
    paddingBottom: 3,
    color: '#FFF',
    textTransform: 'uppercase',
  },
  statusClose: {
    textAlign: 'center',
    fontSize: 14,
    fontWeight: 'bold',
    backgroundColor: 'red',
    borderRadius: 5,
    paddingTop: 3,
    paddingBottom: 3,
    color: '#FFF',
    textTransform: 'uppercase',
  },
  name: {
    fontSize: 18,
    marginVertical: 0,
    fontWeight: 'bold',
  },
  provider: {
    marginTop: 5,
    marginBottom: 5,
    color: '#888',
  },
  contact: {
    marginBottom: 5,
    color: '#888',
  },
  iconSize: {
    fontSize: 16,
  },
  description: {
    fontSize: 16,
    color: '#333',
  },
  footer: {
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  buttonStyle: {
    position: 'absolute',
    top: 0,
    left: '50%',
    zIndex: 99,
    marginTop: -70,
    marginLeft: -35,
    width: 70,
    height: 70,
    backgroundColor: '#EDB43C',
    borderRadius: 60,
  },
  buttonTextStyle: {
    textAlign: 'center',
    color: '#FFF',
    width: 70,
    height: 70,
    paddingVertical: 20,
    fontWeight: 'bold',
  },
  fab: {
    position: 'absolute',
    margin: 16,
    right: 0,
    bottom: 0,
  },
  SectionStyle: {
    flexDirection: 'row',
    height: 40,
    marginBottom: 10,
  },
  lableInput: {
    marginBottom: 40,
    color: '#EDB43C',
    fontSize: 28,
    marginLeft: 15,
    marginRight: 15,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  submitButton: {
    marginTop: 0,
    backgroundColor: '#EDB43C',
    color: '#000',
  },
  errorTextStyle: {
    color: 'red',
    textAlign: 'left',
    fontSize: 14,
    fontWeight: '500',
  },
  textInput: {
    padding: 5,
    color: '#000',
    fontSize: 14,
    fontWeight: '500',
  },
  select: {
    width: '100%',
    borderBottomWidth: 1,
    borderColor: '#000',
    borderRadius: 0,
    paddingHorizontal: 5,
    fontWeight: '500',
  },
  selectField: {
    color: '#000',
    fontSize: 20,
    fontWeight: '500',
  },
  root: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textTextInput: {
    // backgroundColor: '#F5F5F5',
    height: 50,
    flex: 1,
    marginHorizontal: 10,
  },
});
