import EStyleSheet from 'react-native-extended-stylesheet';
import {isIos} from '../../../../constants/appStyles';

export const styles = EStyleSheet.create({
  mainView: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#EDB43C',
  },
  SectionStyle: {
    flexDirection: 'row',
    height: 40,
    marginTop: 20,
  },
  backicon: {
    fontSize: 22,
  },
  container: {
    paddingHorizontal: 15,
  },
  headerImage: {
    marginVertical: 30,
    width: 116,
    height: 120,
  },
  heading: {
    marginLeft: 0,
    fontSize: 40,
    marginBottom: 30,
    fontWeight: 'bold',
    color: '#000',
  },
  pickersection: {
    width: 100,
  },
  titleTextStyle: {
    color: '#000',
    fontSize: 40,
    textAlign: 'left',
    fontWeight: 'bold',
  },
  titleCaptionStyle: {
    marginBottom: 20,
    color: '#000',
    fontSize: 20,
    textAlign: 'left',
    fontWeight: 'bold',
  },
  buttonStyle: {
    backgroundColor: '#000',
    borderWidth: 0,
    color: '#FFFFFF',
    borderColor: '#000',
    height: 50,
    alignItems: 'center',
    borderRadius: 30,
    marginTop: 20,
    marginBottom: 20,
  },
  FlateSelect: {
    color: '#000',
    height: 50,
    paddingLeft: 0,
    paddingRight: 0,
    borderWidth: 1,
    borderBottomWidth: 2,
    borderRadius: 0,
    borderBottomColor: '#000',
    borderColor: '#000',
  },
  buttonTextStyle: {
    color: '#FFF',
    paddingVertical: 14,
    fontSize: 16,
  },
  lableInput: {
    color: '#000',
    fontSize: 18,
    fontWeight: 'bold',
  },
  textInput: {
    flex: 1,
    color: '#000',
    paddingLeft: 0,
    paddingRight: 0,
    borderWidth: 0,
    borderBottomWidth: isIos ? 1 : 0,
    borderRadius: 0,
    borderColor: '#000',
  },
  forgotTextStyle: {
    marginBottom: 30,
    color: '#000',
    textAlign: 'right',
    fontWeight: 'bold',
    fontSize: 14,
  },
  orwithTextStyle: {
    marginBottom: 20,
    color: '#000',
    textAlign: 'center',
    fontSize: 14,
  },
  registerTextStyle: {
    color: '#000',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 14,
  },
  haveAccount: {
    marginBottom: 20,
    color: '#FFF',
    fontSize: 16,
    backgroundColor: '#000',
    paddingHorizontal: 10,
    paddingVertical: 14,
    borderRadius: 30,
    textAlign: 'center',
  },
  errorTextStyle: {
    marginLeft: 35,
    color: 'red',
    textAlign: 'left',
    fontSize: 14,
    fontWeight: 'bold',
  },
  loginButton: {
    marginLeft: 0,
    marginBottom: 20,
    width: '100%',
    backgroundColor: '#000',
    color: '#FFF',
  },
});
